// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPHEBaqI8v-0jZA0SifO4iggh2bhFAYgY',
    appId: '1:956333738143:web:7ad832160dc06b58563aaa',
    messagingSenderId: '956333738143',
    projectId: 'medlink-app-4f92a',
    authDomain: 'medlink-app-4f92a.firebaseapp.com',
    storageBucket: 'medlink-app-4f92a.firebasestorage.app',
    measurementId: 'G-19R474HVPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7GMKIh6FbbYCbNaPeZJO6OcU2kIPD2Q',
    appId: '1:956333738143:android:499e82ea222292d9563aaa',
    messagingSenderId: '956333738143',
    projectId: 'medlink-app-4f92a',
    storageBucket: 'medlink-app-4f92a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxYPPTxF-iGi-Vvu5zhtXoqR6yLCJ-ZjY',
    appId: '1:956333738143:ios:7f4f503fcb50924d563aaa',
    messagingSenderId: '956333738143',
    projectId: 'medlink-app-4f92a',
    storageBucket: 'medlink-app-4f92a.firebasestorage.app',
    iosClientId: '956333738143-qsma41gddk8hs1s9kt0ud113s7gi338v.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.cap-project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxYPPTxF-iGi-Vvu5zhtXoqR6yLCJ-ZjY',
    appId: '1:956333738143:ios:1d3a349b50fab9ae563aaa',
    messagingSenderId: '956333738143',
    projectId: 'medlink-app-4f92a',
    storageBucket: 'medlink-app-4f92a.firebasestorage.app',
    iosClientId: '956333738143-7c8e4fcj26784mumbk1jovima9q1qu3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPHEBaqI8v-0jZA0SifO4iggh2bhFAYgY',
    appId: '1:956333738143:web:ac6f88ff4f77d910563aaa',
    messagingSenderId: '956333738143',
    projectId: 'medlink-app-4f92a',
    authDomain: 'medlink-app-4f92a.firebaseapp.com',
    storageBucket: 'medlink-app-4f92a.firebasestorage.app',
    measurementId: 'G-QDSP28433Y',
  );

}